"""

Revision ID: 206af9856a00
Revises: 8e121e214d42
Create Date: 2026-02-16 22:52:24.187894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '206af9856a00'
down_revision: Union[str, None] = '8e121e214d42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('line_items', sa.Column('line_number', sa.Integer(), nullable=False))
    op.add_column('line_items', sa.Column('sku', sa.String(), nullable=False))
    op.add_column('line_items', sa.Column('name', sa.String(), nullable=False))
    op.add_column('line_items', sa.Column('discount_amount', sa.Numeric(precision=18, scale=2), nullable=False))
    op.add_column('line_items', sa.Column('tax_amount', sa.Numeric(precision=18, scale=2), nullable=False))
    op.add_column('line_items', sa.Column('uom', sa.String(), nullable=True))
    op.add_column('line_items', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('line_items', 'barcode',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('line_items', 'unit_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('line_items', 'quantity',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=False)
    op.alter_column('line_items', 'line_total',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('line_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_line_items_barcode'), 'line_items', ['barcode'], unique=False)
    op.create_index(op.f('ix_line_items_sku'), 'line_items', ['sku'], unique=False)
    op.create_index('ix_line_items_transaction_line', 'line_items', ['transaction_id', 'line_number'], unique=True)
    op.drop_column('line_items', 'product_name')
    op.drop_column('line_items', 'sku_id')
    op.add_column('outbox', sa.Column('store_id', sa.String(), nullable=False))
    op.add_column('outbox', sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False))
    op.create_index('ix_outbox_published_id', 'outbox', ['published_at', 'id'], unique=False)
    op.add_column('transactions', sa.Column('receipt_number', sa.String(), nullable=False))
    op.add_column('transactions', sa.Column('tax_amount', sa.Numeric(precision=18, scale=2), nullable=False))
    op.add_column('transactions', sa.Column('total', sa.Numeric(precision=18, scale=2), nullable=False))
    op.add_column('transactions', sa.Column('currency', sa.String(), nullable=False))
    op.add_column('transactions', sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('transactions', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('transactions', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('transactions', sa.Column('client_created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('transactions', sa.Column('note', sa.Text(), nullable=True))
    op.alter_column('transactions', 'subtotal',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('transactions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_transactions_store_terminal_started', 'transactions', ['store_id', 'terminal_id', 'started_at'], unique=False)
    op.create_unique_constraint('uq_transactions_store_receipt', 'transactions', ['store_id', 'receipt_number'])
    op.drop_column('transactions', 'total_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('total_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_constraint('uq_transactions_store_receipt', 'transactions', type_='unique')
    op.drop_index('ix_transactions_store_terminal_started', table_name='transactions')
    op.alter_column('transactions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('transactions', 'subtotal',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.drop_column('transactions', 'note')
    op.drop_column('transactions', 'client_created_at')
    op.drop_column('transactions', 'cancelled_at')
    op.drop_column('transactions', 'completed_at')
    op.drop_column('transactions', 'started_at')
    op.drop_column('transactions', 'currency')
    op.drop_column('transactions', 'total')
    op.drop_column('transactions', 'tax_amount')
    op.drop_column('transactions', 'receipt_number')
    op.drop_index('ix_outbox_published_id', table_name='outbox')
    op.drop_column('outbox', 'occurred_at')
    op.drop_column('outbox', 'store_id')
    op.add_column('line_items', sa.Column('sku_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('line_items', sa.Column('product_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index('ix_line_items_transaction_line', table_name='line_items')
    op.drop_index(op.f('ix_line_items_sku'), table_name='line_items')
    op.drop_index(op.f('ix_line_items_barcode'), table_name='line_items')
    op.alter_column('line_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('line_items', 'line_total',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('line_items', 'quantity',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('line_items', 'unit_price',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('line_items', 'barcode',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('line_items', 'updated_at')
    op.drop_column('line_items', 'uom')
    op.drop_column('line_items', 'tax_amount')
    op.drop_column('line_items', 'discount_amount')
    op.drop_column('line_items', 'name')
    op.drop_column('line_items', 'sku')
    op.drop_column('line_items', 'line_number')
    # ### end Alembic commands ###
